global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Replace with your actual Node Exporter address.

  - job_name: 'my_application'
    static_configs:
      - targets: ['my_app_host:my_app_port'] # Replace with your application's metrics endpoint.

